//level information

export let LevelsData = {
  1: {
    'exp': 0,
    'newStats': 'none',
    'atWill': 2,
    'encounter': 1,
    'daily': 1,
    'utility': 0,
    'feat': 1,
  },
  2: {
    'exp': 1000,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 0,
    'daily': 0,
    'utility': 1,
    'feat': 1,
  },
  3: {
    'exp': 2250,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 1,
    'daily': 0,
    'utility': 0,
    'feat': 0,
  },
  4: {
    'exp': 3750,
    'newStats': 'chooseTwo',
    'atWill': 0,
    'encounter': 0,
    'daily': 0,
    'utility': 0,
    'feat': 1,
  },
  5: {
    'exp': 5500,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 0,
    'daily': 1,
    'utility': 0,
    'feat': 0,
  },
  6: {
    'exp': 7500,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 0,
    'daily': 0,
    'utility': 1,
    'feat': 1,
  },
  7: {
    'exp': 10000,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 1,
    'daily': 0,
    'utility': 0,
    'feat': 0,
  },
  8: {
    'exp': 13000,
    'newStats': 'chooseTwo',
    'atWill': 0,
    'encounter': 0,
    'daily': 0,
    'utility': 0,
    'feat': 1,
  },
  9: {
    'exp': 16500,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 0,
    'daily': 1,
    'utility': 0,
    'feat': 0,
  },
  10: {
    'exp': 20500,
    'newStats': 'none',
    'atWill': 0,
    'encounter': 0,
    'daily': 0,
    'utility': 1,
    'feat': 1,
  },
}
